2025-10-08 23:04:02,144 [PID 370901] DEBUG Using selector: EpollSelector
2025-10-08 23:04:02,149 [PID 370901] INFO Reading Pyre server configurations...
2025-10-08 23:04:02,151 [PID 370901] ERROR Uncaught error in persistent.run
Traceback (most recent call last):
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/persistent.py", line 299, in run
    return asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/persistent.py", line 224, in run_persistent
    initial_server_options = pyre_server_options.read_server_options(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 129, in read_server_options
    return server_options_reader()
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 114, in read
    return PyreServerOptions.create(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 93, in create
    start_arguments = start.create_server_arguments(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/start.py", line 311, in create_server_arguments
    source_paths = backend_arguments.get_source_path_for_server(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/backend_arguments.py", line 418, in get_source_path_for_server
    return get_source_path(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/backend_arguments.py", line 397, in get_source_path
    raise configuration_module.InvalidConfiguration(
pyre_check.client.configuration.exceptions.InvalidConfiguration: Invalid configuration: Cannot find any source files to analyze. Either `source_directories` or `targets` must be specified.
2025-10-08 23:14:13,129 [PID 371613] DEBUG Using selector: EpollSelector
2025-10-08 23:14:13,131 [PID 371613] INFO Reading Pyre server configurations...
2025-10-08 23:14:13,136 [PID 371613] ERROR Uncaught error in persistent.run
Traceback (most recent call last):
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/persistent.py", line 299, in run
    return asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/persistent.py", line 224, in run_persistent
    initial_server_options = pyre_server_options.read_server_options(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 129, in read_server_options
    return server_options_reader()
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 114, in read
    return PyreServerOptions.create(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 93, in create
    start_arguments = start.create_server_arguments(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/start.py", line 311, in create_server_arguments
    source_paths = backend_arguments.get_source_path_for_server(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/backend_arguments.py", line 418, in get_source_path_for_server
    return get_source_path(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/backend_arguments.py", line 397, in get_source_path
    raise configuration_module.InvalidConfiguration(
pyre_check.client.configuration.exceptions.InvalidConfiguration: Invalid configuration: Cannot find any source files to analyze. Either `source_directories` or `targets` must be specified.
2025-10-09 01:41:53,466 [PID 380627] DEBUG Using selector: EpollSelector
2025-10-09 01:41:53,469 [PID 380627] INFO Reading Pyre server configurations...
2025-10-09 01:41:53,472 [PID 380627] ERROR Uncaught error in persistent.run
Traceback (most recent call last):
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/persistent.py", line 299, in run
    return asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/persistent.py", line 224, in run_persistent
    initial_server_options = pyre_server_options.read_server_options(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 129, in read_server_options
    return server_options_reader()
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 114, in read
    return PyreServerOptions.create(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 93, in create
    start_arguments = start.create_server_arguments(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/start.py", line 311, in create_server_arguments
    source_paths = backend_arguments.get_source_path_for_server(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/backend_arguments.py", line 418, in get_source_path_for_server
    return get_source_path(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/backend_arguments.py", line 397, in get_source_path
    raise configuration_module.InvalidConfiguration(
pyre_check.client.configuration.exceptions.InvalidConfiguration: Invalid configuration: Cannot find any source files to analyze. Either `source_directories` or `targets` must be specified.
