##[pylyzer] succeed c:\users\esteban\desktop\crso_python\17_manejo_de_archivos\248_manejoarchivosenpython.py 1758233499 514
.archivo: global::File!


.e: global::Exception



