2025-10-07 20:14:50,118 [PID 28764] DEBUG Using selector: EpollSelector
2025-10-07 20:14:50,125 [PID 28764] INFO Reading Pyre server configurations...
2025-10-07 20:14:50,134 [PID 28764] ERROR Uncaught error in persistent.run
Traceback (most recent call last):
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/persistent.py", line 299, in run
    return asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/persistent.py", line 224, in run_persistent
    initial_server_options = pyre_server_options.read_server_options(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 129, in read_server_options
    return server_options_reader()
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 114, in read
    return PyreServerOptions.create(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 93, in create
    start_arguments = start.create_server_arguments(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/start.py", line 311, in create_server_arguments
    source_paths = backend_arguments.get_source_path_for_server(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/backend_arguments.py", line 418, in get_source_path_for_server
    return get_source_path(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/backend_arguments.py", line 397, in get_source_path
    raise configuration_module.InvalidConfiguration(
pyre_check.client.configuration.exceptions.InvalidConfiguration: Invalid configuration: Cannot find any source files to analyze. Either `source_directories` or `targets` must be specified.
2025-10-08 22:53:21,586 [PID 367246] DEBUG Using selector: EpollSelector
2025-10-08 22:53:21,601 [PID 367246] INFO Reading Pyre server configurations...
2025-10-08 22:53:21,621 [PID 367246] ERROR Uncaught error in persistent.run
Traceback (most recent call last):
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/persistent.py", line 299, in run
    return asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/persistent.py", line 224, in run_persistent
    initial_server_options = pyre_server_options.read_server_options(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 129, in read_server_options
    return server_options_reader()
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 114, in read
    return PyreServerOptions.create(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/pyre_server_options.py", line 93, in create
    start_arguments = start.create_server_arguments(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/commands/start.py", line 311, in create_server_arguments
    source_paths = backend_arguments.get_source_path_for_server(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/backend_arguments.py", line 418, in get_source_path_for_server
    return get_source_path(
  File "/home/estefy/.local/share/nvim/mason/packages/pyre/venv/lib/python3.10/site-packages/pyre_check/client/backend_arguments.py", line 397, in get_source_path
    raise configuration_module.InvalidConfiguration(
pyre_check.client.configuration.exceptions.InvalidConfiguration: Invalid configuration: Cannot find any source files to analyze. Either `source_directories` or `targets` must be specified.
